version: "3"
   
services:


  mdb:
      image: mariadb
      command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      restart: always
      environment:
          - MYSQL_ROOT_PASSWORD=mariadb
      
  frontend-dev:
    build: 
      context: ./psifos-frontend
      dockerfile: Dockerfile.dev 
    environment:
      - WATCHPACK_POLLING=true

    command: npm start 
    volumes: 
      - ./psifos-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true


  back-op-dev:
      build: 
        context: ./psifos-backend-op
        dockerfile: Dockerfile.dev

      environment:
        - USER=root
        - PASSWORD=backend
        - NAME_DATABASE=backedn
        - HOST=backedn
        - TYPE_AUTH=cas

      ports:
        - "8000:8000"

      depends_on:
        - mdb